modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="hyrule_chickens"
version="1.0.0"
displayName="Hyrule Chickens"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Wes-PC, MCreator"

[[dependencies.hyrule_chickens]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




